### ISSUE TITLE
Dark mode needs work.

### ISSUE THREAD

**Issue by trip5** [Morcatko/EspHome-Editor#21]
I realize you're in early development but I hope you keep it up!  Just installed but will test further later... it looks pretty useful!

Dark mode is... a bit too dark!  I'm on Brave Browser and still getting to know it but I'm guessing it swapped your white background for black and that was it?  Sorry, I'm totally out of touch with Web coding these days so I'm not even sure how light/dark mode works... 

![image](https://github.com/user-attachments/assets/c063af81-e53b-4873-8c7f-f72a6a3a6e0d)

I switched to light mode, went back to the tab, and it looks good (everything blindingly white)... switched back to dark mode and it now it kind of looks like it was probably meant to look in dark mode (although the editor is still white).

![image](https://github.com/user-attachments/assets/8fc78830-6098-4a67-a178-c66f2d051ff8)

...but a reload resets it back grey on black.  Not sure what's going on there.

I realize this probably isn't at the top of your priority list.  Just adding it here in hopes it can look as good as ESPHome's dark mode.

**Comment by Morcatko** [comment]
Hello,
You are correct this project is in very early stage and dark mode is not on top of my todo list. I have not even tested dark mode yet.
Anyway the changes needed to make it somehow work seem to be minimal so I can look at it and I will see if there is something I can do right now.

**Comment by Morcatko** [comment]
Working version released in v0.2.0.
It is not great but IMHO good enough for now. I will revisit it later

**Comment by trip5** [comment]
Just updated my Docker container.  That's good enough for now, for sure!  Thank you!
